#!/bin/bash
echo $(( $(echo $WATER | fold -w1 | while read -r c; do echo -n $(( $(expr index "ewatr" "$c") - 1 )); done) + $(echo $STIR | fold -w1 | while read -r c; do echo -n $(( $(expr index "ti.ir" "$c") - 1 )); done) )) | fold -w1 | while read -r c; do printf "%c" "$((98 + c))"; done; echo
